# Análisis de Ventas E-commerce

**Contexto de negocio:** Eres el analista de datos de una tienda en línea de tecnología. La gerencia comercial te pidió un análisis para entender qué está funcionando bien, dónde hay fugas de ingreso y qué recomendaciones puedes dar para el próximo trimestre.

**Dataset:** `../data/ventas_ecommerce.csv` — pedidos de un año completo (2024), con columnas de producto, cliente, ciudad de envío, método de pago, canal de venta, calificación y estado del pedido.

**Importante:** este dataset viene "sucio" a propósito (nulos, duplicados, inconsistencias de texto, algunos valores negativos por error de captura). Parte del análisis es documentar cómo lo limpiaste y por qué — eso es tan valioso en un portafolio como el análisis en sí.

## Parte 1: Carga y diagnóstico inicial

a) Carga el CSV y revisa forma, tipos de datos y primeras filas.

b) Antes de limpiar nada, **documenta** (en una celda de markdown debajo) qué problemas encuentras: ¿cuántos nulos por columna? ¿cuántos duplicados? ¿algo raro en los valores de `cantidad` o `producto`?

In [7]:
import pandas as pd
# Tu código aquí
df = pd.read_csv('../data/ventas_ecommerce.csv')
df.head()

,id_pedido,fecha_pedido,id_cliente,producto,cantidad,ciudad_envio,metodo_pago,canal_venta,calificacion_cliente,categoria,precio_unitario,total_pedido,estado_pedido
0,ORD-10033,2024-02-08 17:21:59,CUST-1322,Webcam HD 1080p,1,Ciudad de Mexico,Transferencia,App movil,NaN,Accesorios,715.61,715.61,Completado
1,ORD-11021,2024-11-30 22:00:43,CUST-1013,Impresora Multifuncional,5,Queretaro,Transferencia,Sitio web,5.0,Oficina,2389.20,11946.00,Completado
2,ORD-10737,2024-05-04 09:15:47,CUST-1398,Bocina Portatil,1,Ciudad de Mexico,Tarjeta de credito,Sitio web,5.0,Accesorios,816.89,816.89,Completado
3,ORD-11877,2024-07-18 17:09:22,CUST-1019,Webcam HD 1080p,1,Queretaro,Tarjeta de credito,Sitio web,4.0,Accesorios,648.64,648.64,Cancelado
4,ORD-10514,2024-12-14 20:41:43,CUST-1081,Audifonos Bluetooth,5,Queretaro,Efectivo contra entrega,Sitio web,NaN,Accesorios,817.67,4088.35,Completado

*comentarios
-Encontre tiendas con inventarios negativos
-Pedidos sin direccion
-Compras sin calificacion del usuario
-Compras completadas pero mal ubicadas haciendo un mal inventario

## Parte 2: Limpieza de datos

Con base en lo que documentaste arriba, limpia el dataset:

a) Elimina espacios extra en la columna `producto` (pista: `.str.strip()`).

b) Estandariza `ciudad_envio` para que todo esté en el mismo formato de mayúsculas/minúsculas (pista: `.str.title()`).

c) Elimina las filas duplicadas.

d) Decide qué hacer con los nulos de `ciudad_envio` (¿rellenar con "Desconocida" o eliminar? Justifica tu decisión en una celda de markdown).

e) Investiga las filas donde `cantidad` es negativa. ¿Son errores de captura o devoluciones legítimas? Decide y corrige (pista: usa `.abs()` si son errores, o créales una bandera si son casos válidos).

f) Convierte `fecha_pedido` a datetime si no lo está.

In [8]:
# a) Elimina espacios en blanco al inicio/final del texto 
# en la columna 'producto'
df['producto'] = df['producto'].str.strip()
df.head()

,id_pedido,fecha_pedido,id_cliente,producto,cantidad,ciudad_envio,metodo_pago,canal_venta,calificacion_cliente,categoria,precio_unitario,total_pedido,estado_pedido
0,ORD-10033,2024-02-08 17:21:59,CUST-1322,Webcam HD 1080p,1,Ciudad de Mexico,Transferencia,App movil,NaN,Accesorios,715.61,715.61,Completado
1,ORD-11021,2024-11-30 22:00:43,CUST-1013,Impresora Multifuncional,5,Queretaro,Transferencia,Sitio web,5.0,Oficina,2389.20,11946.00,Completado
2,ORD-10737,2024-05-04 09:15:47,CUST-1398,Bocina Portatil,1,Ciudad de Mexico,Tarjeta de credito,Sitio web,5.0,Accesorios,816.89,816.89,Completado
3,ORD-11877,2024-07-18 17:09:22,CUST-1019,Webcam HD 1080p,1,Queretaro,Tarjeta de credito,Sitio web,4.0,Accesorios,648.64,648.64,Cancelado
4,ORD-10514,2024-12-14 20:41:43,CUST-1081,Audifonos Bluetooth,5,Queretaro,Efectivo contra entrega,Sitio web,NaN,Accesorios,817.67,4088.35,Completado

In [9]:
# b) # Esto evita que "cdmx", "CDMX" y "Cdmx" se 
# traten como valores distintos
df['ciudad_envio'] = df['ciudad_envio'].str.strip().str.title()
df.head()

,id_pedido,fecha_pedido,id_cliente,producto,cantidad,ciudad_envio,metodo_pago,canal_venta,calificacion_cliente,categoria,precio_unitario,total_pedido,estado_pedido
0,ORD-10033,2024-02-08 17:21:59,CUST-1322,Webcam HD 1080p,1,Ciudad De Mexico,Transferencia,App movil,NaN,Accesorios,715.61,715.61,Completado
1,ORD-11021,2024-11-30 22:00:43,CUST-1013,Impresora Multifuncional,5,Queretaro,Transferencia,Sitio web,5.0,Oficina,2389.20,11946.00,Completado
2,ORD-10737,2024-05-04 09:15:47,CUST-1398,Bocina Portatil,1,Ciudad De Mexico,Tarjeta de credito,Sitio web,5.0,Accesorios,816.89,816.89,Completado
3,ORD-11877,2024-07-18 17:09:22,CUST-1019,Webcam HD 1080p,1,Queretaro,Tarjeta de credito,Sitio web,4.0,Accesorios,648.64,648.64,Cancelado
4,ORD-10514,2024-12-14 20:41:43,CUST-1081,Audifonos Bluetooth,5,Queretaro,Efectivo contra entrega,Sitio web,NaN,Accesorios,817.67,4088.35,Completado

In [10]:
# c) Elimina filas duplicadas
#  conservando la primera aparición
duplicados_antes = df.duplicated().sum()
df = df.drop_duplicates()
print(f"Se eliminaron {duplicados_antes} filas duplicadas")

Se eliminaron 25 filas duplicadas

d) ### Decisión sobre nulos en ciudad_envio

Decidí **rellenar los nulos con "Desconocida"** en lugar de eliminar las filas, porque:
- Cada fila representa un pedido, y perder esa información (producto, cantidad, fecha)
  significa perder ventas reales del análisis.
- La ciudad de envío es un dato secundario para muchos análisis (ej. ventas por producto),
  así que no vale la pena sacrificar toda la fila por ese único dato faltante.
- Si más adelante se necesita analizar específicamente por ciudad, esos registros
  "Desconocida" simplemente se pueden filtrar o excluir en ese análisis puntual.

In [11]:
# d) Rellena los valores nulos de ciudad_envio con "Desconocida" en vez de eliminarlos,
# para no perder el resto de la información del pedido (ver justificación arriba)
df['ciudad_envio'] = df['ciudad_envio'].fillna('Desconocida')

In [12]:
# e) Investigamos primero cuántas filas tienen cantidad negativa
negativos = df[df['cantidad'] < 0]
print(f"Filas con cantidad negativa: {len(negativos)}")
print(negativos)

Filas con cantidad negativa: 10
      id_pedido         fecha_pedido id_cliente            producto  cantidad  \
77    ORD-10171  2024-10-17 00:00:14  CUST-1338   Monitor Curvo 27"        -5
293   ORD-11753  2024-02-15 06:37:40  CUST-1095  Tablet 10 pulgadas        -4
431   ORD-10481  2024-03-30 23:11:50  CUST-1254  Cargador USB-C 65W        -1
857   ORD-10016  2024-03-16 18:02:46  CUST-1384    Silla Ergonomica        -3
1054  ORD-10789  2024-06-29 13:48:09  CUST-1217  Cargador USB-C 65W        -1
1113  ORD-10847  2024-07-09 08:59:15  CUST-1059      Smartwatch Fit        -5
1291  ORD-11195  2024-02-15 03:20:51  CUST-1240    Laptop Gamer X15        -3
1440  ORD-10167  2024-02-15 10:37:52  CUST-1339   Monitor Curvo 27"        -4
1657  ORD-10322  2024-08-15 11:47:59  CUST-1039      Smartwatch Fit        -3
1800  ORD-10978  2024-05-10 08:00:18  CUST-1212     Webcam HD 1080p        -2

          ciudad_envio              metodo_pago canal_venta  \
77           Monterrey  Efectivo contra entrega   App movil
293        Guadalajara  Efectivo contra entrega   App movil
431   Ciudad De Mexico            Transferencia   App movil
857          Monterrey            Transferencia   App movil
1054       Guadalajara  Efectivo contra entrega   Sitio web
1113         Monterrey       Tarjeta de credito   App movil
1291            Merida                   PayPal   App movil
1440  Ciudad De Mexico            Transferencia   App movil
1657            Merida        Tarjeta de debito   App movil
1800         Monterrey       Tarjeta de credito   App movil

      calificacion_cliente   categoria  precio_unitario  total_pedido  \
77                     5.0     Computo          5925.85     -29629.25
293                    NaN     Computo          4601.63     -18406.52
431                    5.0  Accesorios           418.53       -418.53
857                    3.0     Oficina          3165.35      -9496.05
1054                   3.0  Accesorios           422.99       -422.99
1113                   NaN   Wearables          2708.64     -13543.20
1291                   5.0     Computo         17094.70     -51284.10
1440                   3.0     Computo          7038.78     -28155.12
1657                   5.0   Wearables          2439.95      -7319.85
1800                   5.0  Accesorios           717.66      -1435.32

     estado_pedido
77       Cancelado
293     Completado
431      Cancelado
857     Completado
1054    Completado
1113    Completado
1291    Completado
1440     Cancelado
1657    Completado
1800    Completado

In [13]:
# Digo que son devoluciones legítimas (casos válidos)
# Creamos una bandera para identificarlas y conservamos el valor original
df['es_devolucion'] = df['cantidad'] < 0

In [14]:
# f) Convierte la columna fecha_pedido a formato datetime
# errors='coerce' convierte fechas inválidas en NaT en vez de detener el proceso
df['fecha_pedido'] = pd.to_datetime(df['fecha_pedido'], errors='coerce')

# Verificamos si quedó alguna fecha no convertida (NaT)
print(f"Fechas no convertidas: {df['fecha_pedido'].isna().sum()}")

Fechas no convertidas: 0

In [15]:
# Guarda el dataset limpio en la misma carpeta que el archivo original
df.to_excel('../data/ventas_ecommerce_limpio.xlsx', index=False)
print("Archivo Excel guardado exitosamente en la carpeta data/")

Archivo Excel guardado exitosamente en la carpeta data/

## Parte 3: Preguntas de negocio

Responde cada una con código. Usa solo pedidos con `estado_pedido == 'Completado'` para las preguntas de ingresos (los cancelados/devueltos no deberían contar como venta real — piénsalo, ¿por qué?).

**a)** ¿Cuáles son los 5 productos que más ingresos generaron en el año?

**b)** ¿Cuál es el ingreso total por mes? ¿Hay estacionalidad (meses claramente más fuertes)?

**c)** ¿Qué ciudad tiene el ticket promedio más alto?

**d)** ¿Qué método de pago se usa más, y cuál genera más ingresos en promedio por pedido?

**e)** ¿Qué porcentaje de pedidos totales fueron cancelados o devueltos? ¿Se concentra en algún producto o categoría en particular?

**f)** ¿Cuál es la calificación promedio de cliente por categoría de producto? ¿Hay alguna categoría con calificaciones notablemente bajas que valga la pena investigar?

**g)** ¿Qué canal de venta (App móvil / Sitio web / Marketplace) genera más ingresos totales? ¿Y cuál tiene el ticket promedio más alto?

In [ ]:
# a) Tu código aquí

In [ ]:
# b) Tu código aquí

In [ ]:
# c) Tu código aquí

In [ ]:
# d) Tu código aquí

In [ ]:
# e) Tu código aquí

In [ ]:
# f) Tu código aquí

In [ ]:
# g) Tu código aquí

## Parte 4: Visualización

Crea al menos 3 gráficos que apoyen tus hallazgos anteriores. Sugerencias:

a) Gráfico de línea: ingresos por mes a lo largo del año.

b) Gráfico de barras: top 5 productos por ingreso.

c) Gráfico de barras o pie: distribución de ingresos por canal de venta o método de pago.

Usa `matplotlib` o `seaborn`. Ponle título, etiquetas de ejes y que sea legible — esto es lo que vas a poner en tu README o en una diapositiva.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Tu código aquí

## Parte 5: Exporta datos limpios para Power BI

Guarda tu DataFrame ya limpio como un nuevo CSV (`ventas_limpio.csv`) en la carpeta `data/`. Este será el archivo que conectes a Power BI para construir el dashboard.

Pista: `df.to_csv('../data/ventas_limpio.csv', index=False)`

In [ ]:
# Tu código aquí

## Parte 6: Conclusiones (para tu README)

Escribe aquí, en 4-6 líneas, tus hallazgos principales y 2-3 recomendaciones de negocio basadas en los datos. Esto lo vas a copiar/adaptar al `README.md` del proyecto — es la parte que un reclutador realmente lee.

*(Tus conclusiones aquí)*